// Country list and US tax-treaty table for the W-8 forms.
// Ported from rsv.pizza (frontend/src/utils/countries.ts and taxTreaties.ts,
// IRS Publication 901-derived). General guidance only, not tax advice.
(function () {
const TAX_TREATY_DATA = {
  // Europe — treaty countries (0% on Other Income, no US PE)
  GB: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  IE: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  FR: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  DE: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  NL: { hasTreaty: true, article: "Article 23", otherIncomeRate: 0 },
  BE: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  ES: { hasTreaty: true, article: "Article 23", otherIncomeRate: 0 },
  IT: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  CH: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  AT: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  SE: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  NO: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  DK: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  FI: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  IS: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  CZ: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  SK: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  SI: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  PL: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  HU: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  BG: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  RO: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  LV: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  LT: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  EE: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  LU: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  GR: { hasTreaty: true, article: "Article XIV", otherIncomeRate: 0 },
  TR: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  RU: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0, notes: "US-Russia treaty status is subject to ongoing review \u2014 verify before relying on it." },
  UA: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  CY: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  MT: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  // Americas — treaty countries
  CA: { hasTreaty: true, article: "Article XXII", otherIncomeRate: 0 },
  MX: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  TT: { hasTreaty: true, article: "Article 26", otherIncomeRate: 0 },
  JM: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  BB: { hasTreaty: true, article: "Article 23", otherIncomeRate: 0 },
  VE: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  // Asia / Oceania — treaty countries
  AU: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  NZ: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  JP: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  KR: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  IN: { hasTreaty: true, article: "Article 23", otherIncomeRate: 0 },
  PH: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  ID: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  TH: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  CN: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0, notes: "PRC mainland only \u2014 Hong Kong and Taiwan do not share this treaty." },
  LK: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  BD: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  IL: { hasTreaty: true, article: "Article 27", otherIncomeRate: 0 },
  // Africa — treaty countries
  ZA: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  EG: { hasTreaty: true, article: "Article 24", otherIncomeRate: 0 },
  MA: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  TN: { hasTreaty: true, article: "Article 22", otherIncomeRate: 0 },
  KZ: { hasTreaty: true, article: "Article 21", otherIncomeRate: 0 },
  // No US treaty in force — leave blank, default 30% withholding applies
  BR: { hasTreaty: false, otherIncomeRate: 30 },
  AR: { hasTreaty: false, otherIncomeRate: 30 },
  CL: { hasTreaty: false, otherIncomeRate: 30 },
  PE: { hasTreaty: false, otherIncomeRate: 30, notes: "A US-Peru treaty has been negotiated but is not in force." },
  CO: { hasTreaty: false, otherIncomeRate: 30 },
  UY: { hasTreaty: false, otherIncomeRate: 30 },
  BO: { hasTreaty: false, otherIncomeRate: 30 },
  PY: { hasTreaty: false, otherIncomeRate: 30 },
  EC: { hasTreaty: false, otherIncomeRate: 30 },
  CR: { hasTreaty: false, otherIncomeRate: 30 },
  PA: { hasTreaty: false, otherIncomeRate: 30 },
  GT: { hasTreaty: false, otherIncomeRate: 30 },
  HN: { hasTreaty: false, otherIncomeRate: 30 },
  NI: { hasTreaty: false, otherIncomeRate: 30 },
  SV: { hasTreaty: false, otherIncomeRate: 30 },
  DO: { hasTreaty: false, otherIncomeRate: 30 },
  NG: { hasTreaty: false, otherIncomeRate: 30 },
  GH: { hasTreaty: false, otherIncomeRate: 30 },
  KE: { hasTreaty: false, otherIncomeRate: 30 },
  UG: { hasTreaty: false, otherIncomeRate: 30 },
  TZ: { hasTreaty: false, otherIncomeRate: 30 },
  ET: { hasTreaty: false, otherIncomeRate: 30 },
  DZ: { hasTreaty: false, otherIncomeRate: 30 },
  BW: { hasTreaty: false, otherIncomeRate: 30 },
  CI: { hasTreaty: false, otherIncomeRate: 30 },
  SN: { hasTreaty: false, otherIncomeRate: 30 },
  CM: { hasTreaty: false, otherIncomeRate: 30 },
  GA: { hasTreaty: false, otherIncomeRate: 30 },
  TD: { hasTreaty: false, otherIncomeRate: 30 },
  ML: { hasTreaty: false, otherIncomeRate: 30 },
  BF: { hasTreaty: false, otherIncomeRate: 30 },
  NE: { hasTreaty: false, otherIncomeRate: 30 },
  TG: { hasTreaty: false, otherIncomeRate: 30 },
  BJ: { hasTreaty: false, otherIncomeRate: 30 },
  MW: { hasTreaty: false, otherIncomeRate: 30 },
  ZW: { hasTreaty: false, otherIncomeRate: 30 },
  ZM: { hasTreaty: false, otherIncomeRate: 30 },
  VN: { hasTreaty: false, otherIncomeRate: 30 },
  KH: { hasTreaty: false, otherIncomeRate: 30 },
  LA: { hasTreaty: false, otherIncomeRate: 30 },
  MM: { hasTreaty: false, otherIncomeRate: 30 },
  MN: { hasTreaty: false, otherIncomeRate: 30 },
  HK: { hasTreaty: false, otherIncomeRate: 30, notes: "Hong Kong is not covered by the US-China treaty." },
  TW: { hasTreaty: false, otherIncomeRate: 30, notes: "Taiwan is not covered by the US-China treaty." },
  SA: { hasTreaty: false, otherIncomeRate: 30, notes: "No general income-tax treaty; limited treaty covers shipping/air only." },
  AE: { hasTreaty: false, otherIncomeRate: 30, notes: "No general income-tax treaty; limited treaty covers shipping/air only." },
  LB: { hasTreaty: false, otherIncomeRate: 30 }
};
const NAME_TO_CODE = {
  // Europe
  "united kingdom": "GB",
  "uk": "GB",
  "great britain": "GB",
  "england": "GB",
  "scotland": "GB",
  "wales": "GB",
  "northern ireland": "GB",
  "ireland": "IE",
  "\xE9ire": "IE",
  "eire": "IE",
  "france": "FR",
  "germany": "DE",
  "deutschland": "DE",
  "netherlands": "NL",
  "the netherlands": "NL",
  "holland": "NL",
  "belgium": "BE",
  "spain": "ES",
  "espa\xF1a": "ES",
  "espana": "ES",
  "italy": "IT",
  "italia": "IT",
  "switzerland": "CH",
  "schweiz": "CH",
  "suisse": "CH",
  "svizzera": "CH",
  "austria": "AT",
  "\xF6sterreich": "AT",
  "osterreich": "AT",
  "sweden": "SE",
  "sverige": "SE",
  "norway": "NO",
  "norge": "NO",
  "denmark": "DK",
  "danmark": "DK",
  "finland": "FI",
  "suomi": "FI",
  "iceland": "IS",
  "\xEDsland": "IS",
  "island": "IS",
  "czech republic": "CZ",
  "czechia": "CZ",
  "\u010Desko": "CZ",
  "cesko": "CZ",
  "slovakia": "SK",
  "slovak republic": "SK",
  "slovenia": "SI",
  "poland": "PL",
  "polska": "PL",
  "hungary": "HU",
  "magyarorsz\xE1g": "HU",
  "bulgaria": "BG",
  "romania": "RO",
  "latvia": "LV",
  "lithuania": "LT",
  "estonia": "EE",
  "luxembourg": "LU",
  "greece": "GR",
  "turkey": "TR",
  "t\xFCrkiye": "TR",
  "turkiye": "TR",
  "russia": "RU",
  "russian federation": "RU",
  "ukraine": "UA",
  "cyprus": "CY",
  "malta": "MT",
  // Americas
  "canada": "CA",
  "mexico": "MX",
  "m\xE9xico": "MX",
  "trinidad and tobago": "TT",
  "jamaica": "JM",
  "barbados": "BB",
  "venezuela": "VE",
  "brazil": "BR",
  "brasil": "BR",
  "argentina": "AR",
  "chile": "CL",
  "peru": "PE",
  "per\xFA": "PE",
  "colombia": "CO",
  "uruguay": "UY",
  "bolivia": "BO",
  "paraguay": "PY",
  "ecuador": "EC",
  "costa rica": "CR",
  "panama": "PA",
  "panam\xE1": "PA",
  "guatemala": "GT",
  "honduras": "HN",
  "nicaragua": "NI",
  "el salvador": "SV",
  "dominican republic": "DO",
  // Asia / Oceania
  "australia": "AU",
  "new zealand": "NZ",
  "japan": "JP",
  "\u65E5\u672C": "JP",
  "south korea": "KR",
  "korea, republic of": "KR",
  "republic of korea": "KR",
  "korea": "KR",
  "india": "IN",
  "philippines": "PH",
  "indonesia": "ID",
  "thailand": "TH",
  "china": "CN",
  "people's republic of china": "CN",
  "prc": "CN",
  "sri lanka": "LK",
  "bangladesh": "BD",
  "israel": "IL",
  "vietnam": "VN",
  "viet nam": "VN",
  "cambodia": "KH",
  "laos": "LA",
  "lao people's democratic republic": "LA",
  "myanmar": "MM",
  "burma": "MM",
  "mongolia": "MN",
  "hong kong": "HK",
  "taiwan": "TW",
  "saudi arabia": "SA",
  "united arab emirates": "AE",
  "uae": "AE",
  "lebanon": "LB",
  // Africa
  "south africa": "ZA",
  "egypt": "EG",
  "morocco": "MA",
  "tunisia": "TN",
  "kazakhstan": "KZ",
  "nigeria": "NG",
  "ghana": "GH",
  "kenya": "KE",
  "uganda": "UG",
  "tanzania": "TZ",
  "ethiopia": "ET",
  "algeria": "DZ",
  "botswana": "BW",
  "c\xF4te d'ivoire": "CI",
  "cote d'ivoire": "CI",
  "ivory coast": "CI",
  "senegal": "SN",
  "cameroon": "CM",
  "gabon": "GA",
  "chad": "TD",
  "mali": "ML",
  "burkina faso": "BF",
  "niger": "NE",
  "togo": "TG",
  "benin": "BJ",
  "malawi": "MW",
  "zimbabwe": "ZW",
  "zambia": "ZM"
};
function lookupTreaty(country) {
  if (!country) return null;
  const raw = country.trim();
  if (!raw) return null;
  const upper = raw.toUpperCase();
  if (upper.length === 2 && TAX_TREATY_DATA[upper]) {
    return TAX_TREATY_DATA[upper];
  }
  const lower = raw.toLowerCase();
  const code = NAME_TO_CODE[lower];
  if (code && TAX_TREATY_DATA[code]) {
    return TAX_TREATY_DATA[code];
  }
  return null;
}
function normalizeCountryCode(country) {
  if (!country) return null;
  const raw = country.trim();
  if (!raw) return null;
  const upper = raw.toUpperCase();
  if (upper.length === 2 && TAX_TREATY_DATA[upper]) return upper;
  const lower = raw.toLowerCase();
  return NAME_TO_CODE[lower] || null;
}

const COUNTRIES = ["Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bonaire, Sint Eustatius and Saba", "Bosnia and Herzegovina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo", "Congo (Democratic Republic)", "Cook Islands", "Costa Rica", "Côte d'Ivoire", "Croatia", "Cuba", "Curaçao", "Cyprus", "Czechia", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Falkland Islands", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard Island and McDonald Islands", "Holy See", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "North Korea", "North Macedonia", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Romania", "Russia", "Rwanda", "Réunion", "Saint Barthélemy", "Saint Helena, Ascension and Tristan da Cunha", "Saint Kitts and Nevis", "Saint Lucia", "Saint Martin", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Svalbard and Jan Mayen", "Sweden", "Switzerland", "Syria", "São Tomé and Príncipe", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Türkiye", "U.S. Virgin Islands", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Wallis and Futuna", "Western Sahara", "Yemen", "Zambia", "Zimbabwe", "Åland Islands"];
window.TaxData = { COUNTRIES, lookupTreaty, normalizeCountryCode };
})();
